import os
from textwrap import dedent

OUTDIR = "./tool/cfiles/socket_alg"
os.makedirs(OUTDIR, exist_ok=True)

COMMON = dedent(r"""
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <linux/socket.h>
#include <linux/net.h>
#include <linux/if_alg.h>

#ifndef SOL_ALG
#define SOL_ALG 279
#endif

static int make_alg_sock(void){
    int s = socket(AF_ALG, SOCK_SEQPACKET, 0);
    if (s < 0) return -1;
    return s;
}

static int bind_alg(int s, int feat_flag, int mask_flag){
    struct sockaddr_alg sa;
    memset(&sa, 0, sizeof(sa));
    sa.salg_family = AF_ALG;
    memcpy(sa.salg_type, "AUTOGENERATED", 14);
    sa.salg_feat = feat_flag;
    sa.salg_mask = mask_flag;
    memcpy(sa.salg_name, "AUTOGENERATED", 14);
    return bind(s, (struct sockaddr *)&sa, sizeof(sa));
}
""").lstrip()

BASE_SOCKET_BIND = COMMON + dedent(r"""
int main(void){
    int s = make_alg_sock(); if (s < 0) return 0;
    (void)bind_alg(s, 0, 0);
    close(s);
    return 0;
}
""")

SET_KEY = COMMON + dedent(r"""
int main(void){
    int s = make_alg_sock(); if (s < 0) return 0;
    (void)bind_alg(s, 0, 0);
    char k[1] = {0};
    (void)setsockopt(s, SOL_ALG, ALG_SET_KEY, k, sizeof(k));
    close(s);
    return 0;
}
""")

SET_AEAD_AUTHSIZE = COMMON + dedent(r"""
int main(void){
    int s = make_alg_sock(); if (s < 0) return 0;
    (void)bind_alg(s, 0, 0);
    (void)setsockopt(s, SOL_ALG, ALG_SET_AEAD_AUTHSIZE, NULL, 0);
    close(s);
    return 0;
}
""")

ACCEPT = COMMON + dedent(r"""
int main(void){
    int s = make_alg_sock(); if (s < 0) return 0;
    (void)bind_alg(s, 0, 0);
    int c = accept(s, NULL, NULL);
    if (c >= 0) close(c);
    close(s);
    return 0;
}
""")

ACCEPT4 = COMMON + dedent(r"""
#include <fcntl.h>
int main(void){
    int s = make_alg_sock(); if (s < 0) return 0;
    (void)bind_alg(s, 0, 0);
    int c = accept4(s, NULL, NULL, 0);
    if (c >= 0) close(c);
    close(s);
    return 0;
}
""")

SENDMSG = COMMON + dedent(r"""
#include <sys/uio.h>
int main(void){
    int s = make_alg_sock(); if (s < 0) return 0;
    (void)bind_alg(s, 0, 0);
    int c = accept(s, NULL, NULL);
    char b = 0;
    struct iovec iov = {.iov_base=&b, .iov_len=1};
    struct msghdr msg;
    memset(&msg,0,sizeof(msg));
    msg.msg_iov = &iov; msg.msg_iovlen = 1;
    if (c >= 0) { (void)sendmsg(c, &msg, 0); close(c); }
    close(s);
    return 0;
}
""")

SENDMMSG = COMMON + dedent(r"""
#include <sys/uio.h>
#include <sys/syscall.h>
#include <errno.h>
static int my_sendmmsg(int fd, struct mmsghdr *msgvec, unsigned int vlen, unsigned int flags){
#ifdef SYS_sendmmsg
    return syscall(SYS_sendmmsg, fd, msgvec, vlen, flags);
#else
    (void)fd; (void)msgvec; (void)vlen; (void)flags; return -1;
#endif
}
int main(void){
    int s = make_alg_sock(); if (s < 0) return 0;
    (void)bind_alg(s, 0, 0);
    int c = accept(s, NULL, NULL);
    char b = 0;
    struct iovec iov = {.iov_base=&b, .iov_len=1};
    struct msghdr m; memset(&m,0,sizeof(m));
    m.msg_iov = &iov; m.msg_iovlen = 1;
    struct mmsghdr mv; memset(&mv,0,sizeof(mv));
    mv.msg_hdr = m;
    if (c >= 0) { (void)my_sendmmsg(c, &mv, 1, 0); close(c); }
    close(s);
    return 0;
}
""")

READ = COMMON + dedent(r"""
int main(void){
    int s = make_alg_sock(); if (s < 0) return 0;
    (void)bind_alg(s, 0, 0);
    int c = accept(s, NULL, NULL);
    char buf[1];
    if (c >= 0) { (void)read(c, buf, sizeof(buf)); close(c); }
    close(s);
    return 0;
}
""")

with open(os.path.join(OUTDIR, "socket_bind.c"), "w") as f: f.write(BASE_SOCKET_BIND)
with open(os.path.join(OUTDIR, "setsockopt_key.c"), "w") as f: f.write(SET_KEY)
with open(os.path.join(OUTDIR, "setsockopt_aead_authsize.c"), "w") as f: f.write(SET_AEAD_AUTHSIZE)
with open(os.path.join(OUTDIR, "accept.c"), "w") as f: f.write(ACCEPT)
with open(os.path.join(OUTDIR, "accept4.c"), "w") as f: f.write(ACCEPT4)
with open(os.path.join(OUTDIR, "sendmsg.c"), "w") as f: f.write(SENDMSG)
with open(os.path.join(OUTDIR, "sendmmsg.c"), "w") as f: f.write(SENDMMSG)
with open(os.path.join(OUTDIR, "read.c"), "w") as f: f.write(READ)

af_alg_type_flags = [
    "CRYPTO_ALG_TYPE_MASK",
    "CRYPTO_ALG_TYPE_CIPHER",
    "CRYPTO_ALG_TYPE_COMPRESS",
    "CRYPTO_ALG_TYPE_AEAD",
    "CRYPTO_ALG_TYPE_SKCIPHER",
    "CRYPTO_ALG_TYPE_HASH",
    "CRYPTO_ALG_TYPE_SHASH",
    "CRYPTO_ALG_TYPE_AHASH",
    "CRYPTO_ALG_TYPE_RNG",
    "CRYPTO_ALG_TYPE_AKCIPHER",
    "CRYPTO_ALG_TYPE_PCOMPRESS",
    "CRYPTO_ALG_LARVAL",
    "CRYPTO_ALG_DEAD",
    "CRYPTO_ALG_DYING",
    "CRYPTO_ALG_ASYNC",
    "CRYPTO_ALG_NEED_FALLBACK",
    "CRYPTO_ALG_TESTED",
    "CRYPTO_ALG_INSTANCE",
    "CRYPTO_ALG_KERN_DRIVER_ONLY",
    "CRYPTO_ALG_INTERNAL",
]

FEAT_TPL = r"""
{common}
int main(void){{
    int s = make_alg_sock(); if (s < 0) return 0;
    (void)bind_alg(s, {flag}, {flag});
    close(s);
    return 0;
}}
""".strip()

for fl in af_alg_type_flags:
    fname = f"bind_feat_{fl.lower()}.c".replace("crypto_alg_", "")
    with open(os.path.join(OUTDIR, fname), "w") as f:
        f.write(FEAT_TPL.format(common=COMMON, flag=fl))

ALGOP_TPL = r"""
{common}
#include <sys/uio.h>
int main(void){{
    int s = make_alg_sock(); if (s < 0) return 0;
    (void)bind_alg(s, 0, 0);
    int c = accept(s, NULL, NULL);
    int op = {op}; (void)op;
    if (c >= 0) {{
        char b = 0;
        struct iovec iov = {{.iov_base=&b, .iov_len=1}};
        struct msghdr msg; memset(&msg,0,sizeof(msg));
        msg.msg_iov = &iov; msg.msg_iovlen = 1;
        (void)sendmsg(c, &msg, 0);
        close(c);
    }}
    close(s);
    return 0;
}}
""".strip()

for op, base in [("ALG_OP_DECRYPT", "sendmsg_op_decrypt.c"),
                 ("ALG_OP_ENCRYPT", "sendmsg_op_encrypt.c")]:
    with open(os.path.join(OUTDIR, base), "w") as f:
        f.write(ALGOP_TPL.format(common=COMMON, op=op))

IV_ASSOC_TPL = r"""
{common}
int main(void){{
    int s = make_alg_sock(); if (s < 0) return 0;
    (void)bind_alg(s, 0, 0);
    size_t ivlen = 1; (void)ivlen;
    int assoc = 0; (void)assoc;
    close(s);
    return 0;
}}
""".strip()

with open(os.path.join(OUTDIR, "cmsg_iv_assoc.c"), "w") as f:
    f.write(IV_ASSOC_TPL.format(common=COMMON))
